# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clean install
        run: |
          cd ./deploy-me-app
          npm ci
      - name: Build project
        run: |
          cd ./deploy-me-app
          npm run build
      - name: Set artifact
        uses: actions/upload-artifact@v3
        with:
          name: DeployMeApp
          path: ./deploy-me-app/dist/**
